java_binary(
    name = "bfs",
    main_class = "sequential.graph.bfs.BreadthFirstTraversal",
    srcs = glob(["*.java"]),
)

java_binary(
    name = "bfs_grid",
    main_class = "sequential.graph.bfs.GridBreadthFirstTraversal",
    srcs = glob(["*.java"]),
)