py_binary(
    name = "dfs_iterative",
    main = "iterative_depth_first_traversal.py",
    srcs = ["iterative_depth_first_traversal.py"],
)

py_binary(
    name = "dfs_recursive",
    main = "recursive_depth_first_traversal.py",
    srcs = ["recursive_depth_first_traversal.py"],
)