load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_binary")

kt_jvm_binary(
    name = "quicksort",
    srcs = ["quicksort/QuickSort.kt"],
    main_class = "sequential.sorting.quicksort.QuickSortKt",
    deps = ["//_util:utils"],
)
