load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_library")

package(default_visibility = ["//src/kotlin:__subpackages__"])


kt_jvm_library(
    name = "utils",
    srcs = glob([
        "*.kt",
    ]),
)