load("@build_bazel_rules_swift//swift:swift.bzl", "swift_binary")

swift_binary(
    name = "dfs_iterative",
    srcs = [
        "IterativeBreadthFirstTraversal.swift",
        "main.swift",
    ],
)

swift_binary(
    name = "dfs_recursive",
    srcs = [
        "RecursiveBreadthFirstTraversal.swift",
        "main.swift",
    ],
)