load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_binary")

kt_jvm_binary(
    name = "sattolo_shuffle",
    srcs = ["SattoloShuffle.kt"],
    main_class = "sequential.shuffling.sattolo.SattoloShuffleKt",
    deps = ["//_util:utils"],
)
