java_binary(
    name = "dfs_iterative",
    main_class = "sequential.graph.dfs.IterativeDepthFirstTraversal",
    srcs = ["IterativeDepthFirstTraversal.java"],
)

java_binary(
    name = "dfs_recursive",
    main_class = "sequential.graph.dfs.RecursiveDepthFirstTraversal",
    srcs = ["RecursiveDepthFirstTraversal.java"],
)