load("@build_bazel_rules_swift//swift:swift.bzl", "swift_binary")

swift_binary(
    name = "bfs",
    srcs = [
        "BreadthFirstTraversal.swift",
        "main.swift",
    ],
)

swift_binary(
    name = "bfs_grid",
    srcs = [
        "GridBreadthFirstTraversal.swift",
        "main.swift",
    ],
)