load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_library")

package(default_visibility = ["//sequential/sorting:__subpackages__"])

kt_jvm_library(
    name = "sort_analysis",
    srcs = glob(["*.kt"]),
)